export const ROLE_SELECT = 'ROLE_SELECT';
export const ROLE_RESET = 'ROLE_RESET';

export const RESOURCE_FETCH_REQUESTED = 'RESOURCE_FETCH_REQUESTED';
export const RESOURCE_FETCH_START = 'RESOURCE_FETCH_START';
export const RESOURCE_FETCH_SUCCESS = 'RESOURCE_FETCH_SUCCESS';
export const RESOURCE_FETCH_SUCCESS_META = 'RESOURCE_FETCH_SUCCESS_META';

export const RESOURCE_FETCH_ERROR = 'RESOURCE_FETCH_ERROR';
export const RESOURCE_FETCH_END = 'RESOURCE_FETCH_END';

export const SNACKBAR_SHOW = 'SNACKBAR_SHOW';
export const SNACKBAR_HIDE = 'SNACKBAR_HIDE';

export const DIALOG_SHOW = 'DIALOG_SHOW';
export const DIALOG_HIDE = 'DIALOG_HIDE';
export const DIALOG_MODIFY = 'DIALOG_MODIFY';

export const FAQ_TOGGLE = 'FAQ_TOGGLE';
export const FAQ_URL = 'FAQ_URL';

export const DRAWER_SHOW = 'DRAWER_SHOW';
export const DRAWER_HIDE = 'DRAWER_HIDE';

export const CART_ITEM_ADD = 'CART_ITEM_ADD';
export const CART_ITEM_REMOVE = 'CART_ITEM_REMOVE';
export const CART_RESET = 'CART_RESET';

export const BOOTH_CHECKED = 'BOOTH_CHECKED';
export const BOOTH_SELECT = 'BOOTH_SELECT';
export const BOOTH_UNSELECT = 'BOOTH_UNSELECT';
export const BOOTHS_RESET = 'BOOTHS_RESET';

export const SEARCH_STARTED = 'SEARCH_STARTED';